'use strict';
const $=s=>document.querySelector(s); const video=$('#video'),canvas=$('#overlay'),ctx=canvas.getContext('2d');
const state={stream:null,model:null,running:false,events:[],lastClasses:new Set(),frames:0,lastFpsAt:performance.now(),loopId:null};
const allowed=new Set(['person','car','truck','bus','bicycle','motorcycle','dog','cat','backpack','handbag','traffic light','stop sign']);
function setStatus(text,live=false){$('#systemStatus').textContent=text;$('#systemDot').classList.toggle('live',live)}
function logEvent(type,data={}){const event={id:crypto.randomUUID(),timestamp:new Date().toISOString(),type,data};state.events.unshift(event);renderEvents()}
function renderEvents(){const el=$('#events');$('#eventCount').textContent=state.events.length;el.innerHTML=state.events.length?state.events.map(e=>'<li><b>'+escapeHtml(e.type)+'</b><br>'+new Date(e.timestamp).toLocaleTimeString()+'</li>').join(''):'<li class="empty">No events recorded.</li>'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadModel(){if(state.model)return;setStatus('Loading detector');if(!window.cocoSsd)throw new Error('Detector library unavailable');state.model=await cocoSsd.load({base:'lite_mobilenet_v2'});setStatus('Detector ready')}
async function startCamera(){if(!$('#consent').checked)return alert('Authorization confirmation is required.');try{await loadModel();state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=state.stream;await video.play();begin('camera')}catch(e){setStatus('Camera blocked');logEvent('SYSTEM_ERROR',{message:e.message});alert('Camera could not start: '+e.message)}}
function begin(source){state.running=true;$('#placeholder').hidden=true;$('#startBtn').disabled=true;$('#stopBtn').disabled=false;$('#captureBtn').disabled=false;setStatus('Analyzing locally',true);logEvent('SOURCE_STARTED',{source});detectLoop()}
function stop(){state.running=false;cancelAnimationFrame(state.loopId);if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;video.pause();video.removeAttribute('src');video.srcObject=null;canvas.width=canvas.height=0;$('#placeholder').hidden=false;$('#startBtn').disabled=false;$('#stopBtn').disabled=true;$('#captureBtn').disabled=true;$('#objectCount').textContent='0';$('#fps').textContent='0';setStatus('Standby');logEvent('SOURCE_STOPPED')}
async function detectLoop(){if(!state.running)return;if(video.readyState>=2){canvas.width=video.videoWidth;canvas.height=video.videoHeight;const predictions=(await state.model.detect(video,30,.45)).filter(p=>allowed.has(p.class));draw(predictions);track(predictions);state.frames++;const now=performance.now();if(now-state.lastFpsAt>=1000){$('#fps').textContent=Math.round(state.frames*1000/(now-state.lastFpsAt));state.frames=0;state.lastFpsAt=now}}state.loopId=requestAnimationFrame(detectLoop)}
function draw(items){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.font=Math.max(13,canvas.width/80)+'px ui-monospace';items.forEach(p=>{const [x,y,w,h]=p.bbox;ctx.strokeStyle='#55f6df';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);const label=p.class.toUpperCase()+' '+Math.round(p.score*100)+'%';const tw=ctx.measureText(label).width+10;ctx.fillStyle='#55f6df';ctx.fillRect(x,Math.max(0,y-22),tw,22);ctx.fillStyle='#02100e';ctx.fillText(label,x+5,Math.max(15,y-6))});$('#objectCount').textContent=items.length;$('#detections').innerHTML=items.length?items.map(p=>'<div class="detection-row"><b>'+escapeHtml(p.class)+'</b><span>'+Math.round(p.score*100)+'%</span></div>').join(''):'<div class="empty">No tracked objects.</div>'}
function track(items){const current=new Set(items.map(x=>x.class));current.forEach(c=>{if(!state.lastClasses.has(c))logEvent('OBJECT_ENTERED',{class:c})});state.lastClasses=current}
async function capture(){const out=document.createElement('canvas');out.width=video.videoWidth;out.height=video.videoHeight;const c=out.getContext('2d');c.drawImage(video,0,0);c.drawImage(canvas,0,0);const blob=await new Promise(r=>out.toBlob(r,'image/jpeg',.9));const bytes=await blob.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='clearglass-evidence-'+Date.now()+'.jpg';a.click();logEvent('EVIDENCE_CAPTURED',{sha256:hash,size:blob.size});}
function exportSession(){const payload={schema:'clearglass.vision.session.v1',exportedAt:new Date().toISOString(),privacy:{processing:'on-device',biometrics:false,automaticRecording:false},events:state.events};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='clearglass-session-'+Date.now()+'.json';a.click()}
$('#startBtn').onclick=startCamera;$('#stopBtn').onclick=stop;$('#captureBtn').onclick=capture;$('#exportBtn').onclick=exportSession;$('#clearBtn').onclick=()=>{state.events=[];renderEvents()};
$('#fileInput').onchange=async e=>{if(!$('#consent').checked){e.target.value='';return alert('Authorization confirmation is required.')}const f=e.target.files[0];if(!f)return;await loadModel();video.srcObject=null;video.src=URL.createObjectURL(f);video.loop=true;await video.play();begin('local-file')};
setInterval(()=>$('#clock').textContent=new Date().toISOString().slice(11,19)+' UTC',1000);window.addEventListener('beforeunload',()=>state.stream?.getTracks().forEach(t=>t.stop()));