"use client";
import React, { type ReactNode } from "react";
import type { ConnectionState, DataFreshness, LiveEvent, LiveSnapshot, StreamName } from "@/lib/live/contracts";

export type LiveViewProps = { initialData?: LiveSnapshot; updates?: LiveEvent[]; loading?: boolean; stale?: boolean; error?: string; disabled?: boolean; empty?: boolean; reducedMotion?: boolean; accessibilityLabel?: string; freshness: DataFreshness };
export function LiveConnectionIndicator({ state }: { state: ConnectionState }) { return <span className={`connection state-${state.toLowerCase()}`} role="status" aria-live="polite"><i aria-hidden />{state === "DISABLED" ? "Live signals off" : state}</span>; }
export function LiveDataBadge({ freshness }: { freshness: DataFreshness }) { return <span className={`data-badge freshness-${freshness.state}`}>{freshness.state === "live" ? "Live now" : freshness.state === "unavailable" ? "Unavailable" : freshness.state}</span>; }
export function LastUpdatedLabel({ freshness }: { freshness: DataFreshness }) { const at = freshness.receivedAt ?? freshness.measuredAt; return <span className="last-updated">{at ? `Measured ${new Date(at).toLocaleString()}` : "No verified measurement"}</span>; }
export function StaleDataNotice({ stale, freshness }: { stale?: boolean; freshness: DataFreshness }) { return stale || freshness.state === "stale" ? <p className="notice amber" role="status">This data is stale. It is not represented as live.</p> : null; }
export function LiveMetricCard({ title, value, ...props }: LiveViewProps & { title: string; value?: ReactNode }) { return <article className="metric-card" aria-label={props.accessibilityLabel ?? title}><header><h3>{title}</h3><LiveDataBadge freshness={props.freshness} /></header>{props.disabled || props.freshness.state === "unavailable" ? <p>No verified source configured.</p> : props.error ? <p role="alert">Temporarily unavailable.</p> : props.loading ? <p>Loading cached snapshot…</p> : props.empty ? <p>No data available.</p> : <strong>{value}</strong>}<LastUpdatedLabel freshness={props.freshness} /></article>; }
export function LiveSignalGrid({ children }: { children: ReactNode }) { return <div className="signal-grid">{children}</div>; }
export function LiveActivityTimeline({ updates = [], freshness }: LiveViewProps) { return <section aria-label="Verified activity timeline"><LiveDataBadge freshness={freshness} />{updates.length ? <ol>{updates.map(e => <li key={e.id}>{e.type} — <time>{new Date(e.occurredAt).toLocaleString()}</time></li>)}</ol> : <p>No verified activity has been published.</p>}</section>; }
export function LiveStatusBanner({ state, message }: { state: ConnectionState; message?: string }) { return <aside className="status-banner" aria-live="polite"><LiveConnectionIndicator state={state} /><span>{message ?? "Static content remains available."}</span></aside>; }
export function LivePerformancePanel(props: LiveViewProps) { return <LiveMetricCard {...props} title="Website performance" empty={!props.updates?.length} />; }
export function LiveSystemMap(props: LiveViewProps) { return <section className="system-map" aria-label={props.accessibilityLabel ?? "System signal map"}><h2>System signal map</h2><p>{props.disabled ? "Live topology disabled." : "Only configured, public signals appear here."}</p><LiveDataBadge freshness={props.freshness} /></section>; }
export function LiveEventStream(props: LiveViewProps) { return <LiveActivityTimeline {...props} />; }
export class LiveErrorBoundary extends React.Component<{ children: ReactNode }, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; } render() { return this.state.failed ? <section role="alert"><p>A live module failed. The rest of this page remains available.</p><button onClick={() => this.setState({ failed: false })}>Retry module</button></section> : this.props.children; } }
export function LiveReconnectButton({ onReconnect, disabled }: { onReconnect(): void; disabled?: boolean }) { return <button type="button" onClick={onReconnect} disabled={disabled}>Refresh snapshot</button>; }
export function LiveDataConsentControl({ enabled, onChange }: { enabled: boolean; onChange(v: boolean): void }) { return <label className="toggle"><input type="checkbox" checked={enabled} onChange={e => onChange(e.target.checked)} /> Allow optional live connections on this device</label>; }
export function LiveStreamToggle({ stream, enabled, onChange }: { stream: StreamName; enabled: boolean; onChange(v: boolean): void }) { return <label className="toggle"><input type="checkbox" checked={enabled} onChange={e => onChange(e.target.checked)} /> {stream} stream</label>; }
